# Servers to Harvest [Mandatory] | URL Endpoint 
harvest_servers:
  # iepnb ogc
  - url: 'https://geoservicios.iepnb.es/geoserver/ows'
    name: 'Geoserver IEPNB'
    # {ckan_site_url}/group/ to ingest the records
    groups: ['geoserver-eikos']
    active: True
    # type based on ckan_info/ckan_harvester types
    type: 'ogc'
    # {ckan_site_url}/organization/ to ingest the records
    organization: 'test'
    default_dcat_info:
      publisher_name: 'Test'
      publisher_email: 'test@iepnb.es'
      publisher_identifier: 'TTEC-TEST'
      publisher_url: 'https://iepnb.es'
      publisher_type: 'https://purl.org/adms/publishertype/NationalAuthority'
      # Default URIs of metadata contact point and resource maintainer
      maintainer_uri: 'https://iepnb.es/catalogodatos/organization/iepnb'
      contact_uri: 'https://iepnb.es/catalogodatos/organization/iepnb'
    # OGC Server workspaces
    workspaces: ['ENP','inenp','RN2000'] 
    # https://inspire.ec.europa.eu/metadata-codelist/TopicCategory
    default_keywords: 
      - name: "test"
        uri: "https://iepnb.es/catalogodatos/organization/test"
      - name: "environment"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/environment"
      - name: "biota"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/biota"
    # https://inspire.ec.europa.eu/theme
    inspireid_theme: 'PS'
    # inspireId = namespace (ej. {inspireid_nutscode}.{inspireid_theme}.{workspace}}) + localId (ej. {layername}) + versionId ({inspireid_versionid})
    # https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes
    inspireid_nutscode: 'ES' 
    inspireid_versionid: ''
    default_provenance: 'Los datos espaciales se han generado a partir del Banco de Datos de la Naturaleza bajo la responsabilidad del Inventario Español del Patrimonio Natural y de la Biodiversidad, en el marco del proyecto EIKOS.'

  # miteco csw
  - url: 'https://www.mapama.gob.es/ide/metadatos/srv/spa/csw'
    name: 'Catalogo MITECO'
    groups: []
    active: True
    type: 'csw'
    organization: 'iepnb'
    default_dcat_info:
      publisher_name: 'Ministerio para la Transición Ecológica y el Reto Demográfico'
      publisher_email: 'buzon-bdatos@miteco.es'
      publisher_identifier: 'E05068001'
      publisher_url: 'https://www.miteco.gob.es'
      publisher_type: 'https://purl.org/adms/publishertype/NationalAuthority'
      # Default URIs of metadata contact point and resource maintainer
      maintainer_uri: 'http://datos.gob.es/recurso/sector-publico/org/Organismo/E05068001'
      contact_uri: 'http://datos.gob.es/recurso/sector-publico/org/Organismo/E05068001'
    default_keywords: 
      - name: "iepnb"
        uri: "https://iepnb.es/catalogodatos/organization/iepnb"
      - name: "environment"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/environment"
      - name: "biota"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/biota"
    inspireid_theme: 'HB'
    # Words to search in the metadata record (owslib: OgcExpression from owslib.fes module)
    constraints: 
      keywords: []
      mails: ['brfranco@miteco.es', 'buzon-bdatos@miteco.es', 'brfranco@mapama.es', 'buzon-bdatos@mapama.es']
    default_bbox: '{"type": "Polygon", "coordinates": [[[-19.0, 27.0], [4.57, 27.0], [4.57, 44.04], [-19.0, 44.04], [-19.0, 27.0]]]}'

  # codsi csw
  - url: 'https://www.idee.es/csw-codsi-idee/srv/spa/csw'
    name: 'CODSI'
    groups: []
    active: False
    type: 'csw'
    organization: 'iepnb'
    default_dcat_info:
      publisher_name: 'Ministerio para la Transición Ecológica y el Reto Demográfico'
      publisher_email: 'buzon-bdatos@miteco.es'
      publisher_identifier: 'E05068001'
      publisher_url: 'https://www.miteco.gob.es'
      publisher_type: 'https://purl.org/adms/publishertype/NationalAuthority'
      # Default URIs of metadata contact point and resource maintainer
      maintainer_uri: 'http://datos.gob.es/recurso/sector-publico/org/Organismo/E05068001'
      contact_uri: 'http://datos.gob.es/recurso/sector-publico/org/Organismo/E05068001'
    default_keywords: 
      - name: "iepnb"
        uri: "https://iepnb.es/catalogodatos/organization/iepnb"
      - name: "environment"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/environment"
      - name: "biota"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/biota"
    inspireid_theme: 'HB'
    constraints: 
      keywords: ['iepnb', 'inventario', 'patrimonio', 'miteco', 'natura']
      mails: ['brfranco@miteco.es', 'buzon-bdatos@miteco.es', 'brfranco@mapama.es', 'buzon-bdatos@mapama.es']
    default_bbox: '{"type": "Polygon", "coordinates": [[[-19.0, 27.0], [4.57, 27.0], [4.57, 44.04], [-19.0, 44.04], [-19.0, 27.0]]]}'

  # demo csw
  - url: 'https://www.mapama.gob.es/ide/metadatos/srv/spa/csw'
    name: 'Catálogo de Demostración'
    groups: []
    active: False
    type: 'csw'
    organization: 'demo'
    default_dcat_info:
      publisher_name: 'Test'
      publisher_email: 'test@iepnb.es'
      publisher_identifier: 'TTEC-TEST'
      publisher_url: 'https://iepnb.es'
      publisher_type: 'https://purl.org/adms/publishertype/NationalAuthority'
      # Default URIs of metadata contact point and resource maintainer
      maintainer_uri: 'http://datos.gob.es/recurso/sector-publico/org/Organismo/E05068001'
      contact_uri: 'http://datos.gob.es/recurso/sector-publico/org/Organismo/E05068001'
    default_keywords: 
      - name: "test"
        uri: "https://iepnb.es/catalogodatos/organization/test"
      - name: "environment"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/environment"
      - name: "biota"
        uri: "https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/biota"
    inspireid_theme: 'AM'
    constraints: 
      keywords: ['iepnb', 'inventario', 'patrimonio', 'miteco', 'natura']
      mails: ['brfranco@miteco.es', 'buzon-bdatos@miteco.es']
    default_bbox: '{"type": "Polygon", "coordinates": [[[-19.0, 27.0], [4.57, 27.0], [4.57, 44.04], [-19.0, 44.04], [-19.0, 27.0]]]}'

# CKAN Parameters [Mandatory]
ckan_info:
  # CKAN instance URL
  ckan_site_url: 'https://iepnb.es/catalogodatos'
  # Authorization key is shown at {ckan_site_url}/user/admin
  authorization_key: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJXWFlpSjJoTDRPcGxCb2ZDbWk3U0VRcjVfTlRRal9sRVJGU3N2V1Y4OFJqdWxody1wbEZQZC1MRGJFd1JwRS02dHNnNjEzczBtZ2VVMW8yciIsImlhdCI6MTY2MjM2MjIxM30.j9g4u2l8xYovkVXZK-AB5wPLxBuIAmS3PNeqWxNscL0'
  default_license: 'https://creativecommons.org/licenses/by/4.0/'
  # ID list: {ckan_site_url}/api/3/action/license_list
  license_id: 'cc-by'
  # Type of server to harvest (info of servers in 'harvest_servers')
  ckan_harvester:
    - name: csw_server
      type: csw
      active: True
    - name: ogc_server
      type: ogc
      active: True

# Parameters for mnrdb_config script  [Mandatory]
default:
  log_folder: '/../../../../log/'
  # Execute software with multicore parallel processing
  parallelization: False

# DB connection parameters [Optional]
db_dsn:
  host: 'host'
  port: '5432'
  dbname: 'dbname'
  username: 'username'
  password: 'password'
  
  
